### ISSUE TITLE
How to start the server

### ISSUE THREAD

**Issue by codersquare-com** [romanmatiasko/reti-chess#10]
Hi, i'm fairly new to all nodejs stuff, how do you start this server? And how do you access it from localhost?

**Comment by romanmatiasko** [comment]
Please read README.md, I just updated it with steps how to run the app locally.

**Comment by codersquare-com** [comment]
Thank you Roman
I tried to follow the instruction and this is what i got 
/home/xxxx/reti-chess/bin/www:15
const server = app.listen(app.get('port'), () => {
                                            ^
SyntaxError: Unexpected token )


i'm running on node v0.10, pretty old version, is this the reason?

**Comment by romanmatiasko** [comment]
Yes, you need to upgrade node to v0.12

**Comment by codersquare-com** [comment]
OK Thanks @romanmatiasko , i'll try and let you know of any bugs. Please mention the required version in the Readme as well, that would probably help a lot for others

**Comment by romanmatiasko** [comment]
:+1: just did that, thank you.
