### ISSUE TITLE
updating to node 4?

### ISSUE THREAD

**Issue by omidfi** [romanmatiasko/reti-chess#12]
Hi, do you think it would be too much work to make this work with node 4?

**Comment by romanmatiasko** [comment]
Please try node-v4 branch that I've just created, I tested it with node v4.2.1 and it worked. I'll merge it into master if it works for you.

**Comment by omidfi** [comment]
cool, let me see

**Comment by omidfi** [comment]
after I did 
  npm install winston

it works! Thanks
