### ISSUE TITLE
Inconsistent chess pieces

### ISSUE THREAD

**Issue by cauli** [romanmatiasko/reti-chess#5]
In each browser, the pieces are rendered differently.

Solution: use images (base64 seems easier to implement) to render pieces.

**Comment by romanmatiasko** [comment]
I think custom chess font would be even better, since it could better scale on lower resolutions. Thanks for the tip.

**Comment by cybercoder** [comment]
Hi guys, as a amateur chess player i love chess24.com chess pieces and it's wooden board. @romanmatiasko I can help you to create a chessboard like that if you want & i know a little nodejs too if i can help you in this project, i will be happy

**Comment by romanmatiasko** [comment]
@cybercoder Thanks for the link, I'll check it out. And sure, if you want to contribute feel free to do so, fork the repo and submit a pull request. ;)

**Comment by romanmatiasko** [comment]
I've added Smart Regular chess font to the game for rendering the pieces, so I'm closing this issue.
