### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by cybercoder** [romanmatiasko/reti-chess#7]
I think this project is really great & brilliant. There's some suggestions:
- Use MongoDB or Mysql to save games for watch later, I think Mysql be better.
- Use session and cookie to keep user in game after close window or disconnect at least 90 seconds. and show a counter for reconnect.
- Ability to watch games (Live) by other users & board be flexible & changeable by other users (on client side) to check the variations.
- ability to load a game from a PGN or a FEN string.

Warm Regards

**Comment by cybercoder** [comment]
I did add express-session with mysql, but how can continue the game after disconnect and reconnect?

**Comment by cybercoder** [comment]
@romanmatiasko and there's a business question, how much is enough for you if needed to make this project complete like chess24.com if you think we can talk about that message me on skype.
my skype id : vahid.alimohamadi

Regards

**Comment by romanmatiasko** [comment]
You'd have to modify Socket.io event subscriptions. Currently, after first player is disconnected the game is deleted. You'd want to avoid that and also store FEN of each game. After the client is reconnected, you'd sent FEN from server to client and call an action to flux store to load the FEN. That is currently also not possible, so you'd have to implement that as well.

**Comment by cybercoder** [comment]
@romanmatiasko do you think can we grow this project to something like chess24.com ?

**Comment by romanmatiasko** [comment]
@cybercoder I'm not sure what's your intention. Why do you want to build another chess24.com?

**Comment by cybercoder** [comment]
There's a Iranian chess grand master, he needs a business web site like that. I mean if you are interested i can make a link.

**Comment by romanmatiasko** [comment]
@cybercoder Thanks, this is only side project though, not having time to build anything significantly bigger.

**Comment by cybercoder** [comment]
@romanmatiasko I added session support and save each player session_id into game.players array and add FEN string on each move to game[token].fen.
now every time a window close and open i can control reconnect the player and replace previous socket.id with new one. But there's a little misunderstanding. How i can load board with FEN? have you any idea?

**Comment by romanmatiasko** [comment]
@cybercoder you need to call _chess.load(fen) in [GameStore](../blob/master/src/js/stores/GameStore.js). Are you familiar with React and Flux?

**Comment by cybercoder** [comment]
@romanmatiasko no but i think i should learn react & flux
get a look this : https://github.com/cybercoder/iChess

**Comment by cybercoder** [comment]
@romanmatiasko i solved the reconnection for players and changed the chessboard to rosewood style but your new codes made me confused, so i did it on old version of Reti-chess

**Comment by cybercoder** [comment]
@romanmatiasko there's an array with the variable name "games"
first i wanted to use the DB to store games, but i thought with myself when the games was too many may 5000 games in a row like chess.com then it can be slow the fetch operation, and I'm on two ways of decision making. Use DB in all times or only save the games @ finish time. do you have any idea?

**Comment by romanmatiasko** [comment]
@cybercoder If you want to make it really production ready you need to store the games somewhere else other than variable. All games will be lost if your server crashes, restarts etc. Redis or other key-value store/cache may be appropriate.
